export enum AuthActionTypes {
  CONFIRM_LOGIN = 'CONFIRM_LOGIN',
  FAIL_CONFIRM_LOGIN = 'FAIL_CONFIRM_LOGIN',
  GET_SESSION = 'GET_SESSION',
  SAVE_PROFILE = 'SAVE_PROFILE',
  LOGOUT = 'LOGOUT',
  REMOVE_PROFILE = 'REMOVE_PROFILE'
}
