export enum AuthActionTypes {
  CONFIRM_LOGIN = 'CONFIRM_LOGIN',
  THROW_CONFIRM_LOGIN_ERROR = 'THROW_CONFIRM_LOGIN_ERROR',
  GET_SESSION = 'GET_SESSION',
  THROW_GET_SESSION_ERROR = 'THROW_GET_SESSION_ERROR',
  SAVE_PROFILE = 'SAVE_PROFILE',
  LOGOUT = 'LOGOUT',
  THROW_LOGOUT_ERROR = 'THROW_LOGOUT_ERROR',
  REMOVE_PROFILE = 'REMOVE_PROFILE'
}
